# Generated by Django 4.0.10 on 2023-08-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_site_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicle.site'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
